### ISSUE TITLE
Minimum Python required version is not correct

### ISSUE THREAD

**Issue by fernandobrito** [gouline/dbt-metabase#52]
Hi!

The docs state that this amazing library "Requires Python 3.6 or above", and also `setup.py` states the same.

However, some recently introduced changes (https://github.com/gouline/dbt-metabase/blob/master/dbtmetabase/models/metabase.py#L28) broke that. Using `typing.Literal` requires Python 3.8+. Running the library with Python 3.7 for example will raise:

```
ImportError: cannot import name 'Literal' from 'typing' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
```

Alternatives on what to do:
* Remove this `Literal` type hint and instead use Enum
* Install an extra dependency that will make this type hint work in 3.6+ (see info box on https://mypy.readthedocs.io/en/stable/literal_types.html)
* Bump the minimum required version to 3.8. Maybe a bit overkill just because of a type hint. dbt itself doesn't run well on 3.9, so requiring a minimum of 3.8 leaves a very tight compatibility range. 

Orthogonal to that, we could:
* Explicitly set a Python version (3.6) in the GitHub Actions workflow that runs CI tests using:
```
- uses: actions/setup-python@v2
  with:
    python-version: '3.6.x' 
```
* or, Test multiple Python versions with GitHub Actions matrix https://github.com/actions/setup-python#usage
* or, Test multiple Python versions with `tox`

I'm happy to contribute with a PR once the maintainer and contributors align on how to move forward 😄 .

**Comment by gouline** [comment]
Hmm, interesting!

I think removing `Literal` is fine, since it's just a type annotation and doesn't change any functionality. Definitely wouldn't want to make 3.8 the minimum Python version or introduce an extra dependency just for that.

Also good idea on running the tests in GitHub Actions. Let's start with 3.6 for now and consider the version matrix as a future improvement.

Let me know if you have any other questions to raise a PR for this.

FYI @z3z1ma

**Comment by z3z1ma** [comment]
Thanks for pointing that out! Agreed. I like the Enum class actually. Its still nice and explicit and backwards compatible as fernandobrito pointed out.
